accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views

from accounts.views import login_view
from accounts.views import password_change_view
from accounts.views import sign_up_view
from accounts.views import user_change_view
from accounts.views.user_view import UserViewSet

app_name = 'accounts'

user_list = UserViewSet.as_view({
    'get': 'list'
})
user_detail = UserViewSet.as_view({
    'get': 'retrieve'
})

urlpatterns = [
    url(r'^accounts/modify$', user_change_view.UserChangeView.as_view(), name='change_user'),
    url(r'^accounts/changepassword/$', password_change_view.PasswordChangeView.as_view(), name='change_password'),
    url(r'^join/$', sign_up_view.SignUpView.as_view(), name='sign_up'),
    url(r'^login/$', login_view.LoginView.as_view(), name='log_in'),
    url(r'^logout/$', views.LogoutView.as_view(), name='log_out'),
    url(r'^users/$', user_list, name='user-list'),
    url(r'^users/(?P<pk>[0-9]+)/$', user_detail, name='user-detail')
]

# urlpatterns = [
#     url(r'^users/$', user_view.UserList.as_view(), name='user-list'),
#     url(r'^users/(?P<pk>[0-9]+)/$', user_view.UserDetail.as_view(), name='user-detail'),
# ]

# urlpatterns = format_suffix_patterns(urlpatterns)

home/urls.py
from django.conf.urls import url

from accounts.views import user_view
from home.views import basic_view

app_name = 'home'

urlpatterns = [
    # ex: /polls/
    url(r'^$', basic_view.to_index, name='index_root'),
    url(r'^index$', basic_view.to_index, name='index'),
]

meiju/urls.py
from django.conf.urls import url
from meiju.views import drama_view
from rest_framework.urlpatterns import format_suffix_patterns

from meiju.views import tv_drama_view
from meiju.views.drama_view import DramaViewSet, DramaTypeViewSet

app_name = 'dramas'

drama_list = DramaViewSet.as_view({
    'get': 'list'
})
drama_detail = DramaViewSet.as_view({
    'get': 'retrieve'
})
type_list = DramaTypeViewSet.as_view({
    'get': 'list'
})

urlpatterns = [
    # url(r'^dramas/category/type=(?P<type>.+)/$', tv_drama_view.CategoryDramaView.as_view(), name='drama_category'),
    url(r'^dramas/category/$', tv_drama_view.CategoryDramaView.as_view(), name='drama_category'),
    url(r'^dramas/search/wd=(?P<search_text>.+)/$', tv_drama_view.SearchDramaView.as_view(), name='search_drama'),
    url(r'^dramas/(?P<pk>[0-9]+)/$', tv_drama_view.DramaDetailView.as_view(), name='drama_detail'),
    url(r'^dramas/$', drama_list, name='drama-list'),
    url(r'^drama_type/$', type_list, name='drama-type-list')
]


# urlpatterns = [
#     url(r'^dramas/$', drama_view.DramaList.as_view(), name='drama-list'),
#     url(r'^dramas/(?P<pk>[0-9]+)/$', drama_view.DramaDetail.as_view(), name='drama-detail'),
# ]

# urlpatterns = format_suffix_patterns(urlpatterns)

reviews/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from reviews.views import review_comment_view
from reviews.views import review_like_view
from reviews.views import review_view
from reviews.views.review_view import ReviewViewSet

app_name = 'reviews'

review_list = ReviewViewSet.as_view({
    'get': 'list',
    'post': 'create'
})
review_detail = ReviewViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})

urlpatterns = [
    url(r'^dramas/(?P<pk>[0-9]+)/review/$', review_view.ReviewListView.as_view(), name='review_list'),
    url(r'^reviews/add_review/$', review_view.AddReviewView.as_view(), name='add_review'),
    url(r'^reviews/add_review_comment/$', review_comment_view.AddReviewCommentView.as_view(), name='add_review_comment'),
    url(r'^reviews/add_review_likes/$', review_like_view.AddReviewLikesView.as_view(), name='add_review_likes'),
    url(r'^reviews/delete_review/$', review_view.DeleteReviewView.as_view(), name='delete_review'),
    url(r'^reviews/unwatch_review/$', review_view.AddUnwatchedReviewView.as_view(), name='unwatch_review'),
    url(r'^reviews/delete_review_likes/$', review_like_view.DeleteReviewLikesView.as_view(), name='delete_review_likes'),
    url(r'^reviews/(?P<pk>[0-9]+)/$', review_comment_view.ReviewCommentView.as_view(), name='review_detail'),

    # url(r'^reviews/$', review_list, name='review-list'),
    # url(r'^reviews/(?P<pk>[0-9]+)/$', review_detail, name='review-detail'),
    # url(r'^review-comments/$', review_comment_view.ReviewCommentList.as_view(), name='review-comment-list'),
    # url(r'^review-comments/(?P<pk>[0-9]+)/$', review_comment_view.ReviewCommentDetail.as_view(), name='review-comment-detail'),
]

tv_drama_resys/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# Create a router and register our viewsets with it.
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter
from rest_framework.urlpatterns import format_suffix_patterns

from accounts.views.user_view import UserViewSet
from meiju.views.drama_view import DramaViewSet

# router = DefaultRouter()
# router.register(r'dramas', DramaViewSet)
# router.register(r'users', UserViewSet)

# The API URLs are now determined automatically by the router.
# Additionally, we include the login URLs for the browsable API.


urlpatterns = [
    # url(r'^', include(router.urls)),
    # url('^', include('django.contrib.auth.urls')),
    url(r'^about/$', TemplateView.as_view(template_name="about.html")),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls')),
    url(r'^', include('meiju.urls')),
    url(r'^', include('reviews.urls')),
    url(r'^', include('space.urls')),
    url(r'^', include('home.urls')),
    url(r'^', include('data_visualization.urls')),
]

urlpatterns = format_suffix_patterns(urlpatterns)

meiju/models/cast.py
from django.db import models

from .drama import Drama


class Cast(models.Model):
    drama = models.ForeignKey(Drama, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.drama.title_en + ' : ' + self.name

accounts/forms/sign_up_form.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from accounts import models


class MyCustomedUserCreationForm(UserCreationForm):
    # sex = forms.CharField(widget=forms.Select(
    #         choices=models.MyUser.SEX_CHOICES,
    #         attrs={'class': 'form-control'}
    # ))

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ['email', 'sex', 'date_of_birth', 'nickname']

accounts/views/sign_up_view.py
from django.views.generic import FormView

from accounts import models
from accounts.forms.sign_up_form import MyCustomedUserCreationForm
from tv_drama_resys import settings


class SignUpView(FormView):
    template_name = 'home/sign_up.html'
    form_class = MyCustomedUserCreationForm
    success_url = settings.LOGIN_URL

    def get_context_data(self, **kwargs):
        kwargs = super(SignUpView, self).get_context_data()
        kwargs['sexes'] = models.MyUser.SEX_CHOICES
        return kwargs

    def form_valid(self, form):
        form.save(commit=True)
        return super(SignUpView, self).form_valid(form)

home/views/basic_view.py
from django.db.models import Q
from django.shortcuts import render, redirect

from meiju.models.drama import Drama
from meiju.models.drama_type import DramaType


def to_index(request):
    latest_drama_list = Drama.objects.order_by('-year')[:6]

    types = DramaType.objects

    sci_magic_types = types.filter(Q(type='奇幻') | Q(type='科幻') | Q(type='灾难'))
    sci_magic_dramas = Drama.objects.filter(
        Q(types=sci_magic_types[0]) |
        Q(types=sci_magic_types[1]) |
        Q(types=sci_magic_types[2])
    ).distinct()
    sci_magic_new_dramas = sci_magic_dramas.order_by('-year', '-avg_rating')[:6]
    sci_magic_top10_dramas = sci_magic_dramas.order_by('-avg_rating')[:10]

    supernatural_scary_types = types.filter(Q(type='恐怖') | Q(type='惊悚'))
    supernatural_scary_dramas = Drama.objects.filter(
        Q(types=supernatural_scary_types[0]) |
        Q(types=supernatural_scary_types[1])
    ).distinct()
    supernatural_scary_new_dramas = supernatural_scary_dramas.order_by('-year', '-avg_rating')[:6]
    supernatural_scary_top10_dramas = supernatural_scary_dramas.order_by('-avg_rating')[:10]

    urban_emotional_types = types.filter(Q(type='喜剧') | Q(type='家庭') | Q(type='爱情'))
    urban_emotional_dramas = Drama.objects.filter(
        Q(types=urban_emotional_types[0]) |
        Q(types=urban_emotional_types[1]) |
        Q(types=urban_emotional_types[2])
    ).distinct()
    urban_emotional_new_dramas = urban_emotional_dramas.order_by('-year', '-avg_rating')[:6]
    urban_emotional_top10_dramas = urban_emotional_dramas.order_by('-avg_rating')[:10]

    crime_historic_types = types.filter(Q(type='传记') | Q(type='历史') | Q(type='犯罪'))
    crime_historic_dramas = Drama.objects.filter(
        Q(types=crime_historic_types[0]) |
        Q(types=crime_historic_types[1]) |
        Q(types=crime_historic_types[2])
    ).distinct()
    crime_historic_new_dramas = crime_historic_dramas.order_by('-year', '-avg_rating')[:6]
    crime_historic_top10_dramas = crime_historic_dramas.order_by('-avg_rating')[:10]

    return render(request, 'home/index.html', {
        'sci_magic_new_dramas': sci_magic_new_dramas,
        'sci_magic_top10_dramas': sci_magic_top10_dramas,
        'supernatural_scary_new_dramas': supernatural_scary_new_dramas,
        'supernatural_scary_top10_dramas': supernatural_scary_top10_dramas,
        'urban_emotional_new_dramas': urban_emotional_new_dramas,
        'urban_emotional_top10_dramas': urban_emotional_top10_dramas,
        'crime_historic_new_dramas': crime_historic_new_dramas,
        'crime_historic_top10_dramas': crime_historic_top10_dramas,
    })

space/views/search_view.py
from django.conf import settings
from django.db.models import Q
from django.views.generic import ListView

from accounts.models import MyUser


class PeopleSearchView(ListView):
    template_name = 'space/people_search.html'
    paginate_by = settings.OBJECTS_NUM_PER_PAGE

    def get_queryset(self):
        key = self.kwargs['search_text']
        self.queryset = MyUser.objects.filter(
            (Q(nickname__contains=key) | Q(email__contains=key)) &
            Q(is_admin=False)
        ).exclude(id=self.request.user.id).order_by('-date_joined')

        return super(PeopleSearchView, self).get_queryset()

    def render_to_response(self, context, **response_kwargs):
        followings = self.request.user.followings.all()
        following_arr = []
        for f in followings:
            following_arr.append(f.following_id)
        context['followings'] = following_arr

        context['search_text'] = self.kwargs['search_text']

        return super(PeopleSearchView, self).render_to_response(context, **response_kwargs)

templates/home/category.html
{% extends "base.html" %}

{% block title %}分类{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">剧集索引</div>

            <div class="panel-body">
                <ul id="type_list" class="nav nav-pills" data-value="{{ type }}">
                    {% if type %}
                            <li role="presentation"><a href="{% url 'dramas:drama_category' %}">全部</a></li>
                        {% for t in types %}
                            {% if type == t.id %}
                                <li role="presentation" class="active"><a href="{% url 'dramas:drama_category' %}?type={{ t.id }}">{{ t.type }}</a></li>
                            {% else %}
                                <li role="presentation"><a href="{% url 'dramas:drama_category' %}?type={{ t.id }}">{{ t.type }}</a></li>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                            <li role="presentation" class="active"><a href="{% url 'dramas:drama_category' %}">全部</a></li>
                        {% for t in types %}
                            <li role="presentation"><a href="{% url 'dramas:drama_category' %}?type={{ t.id }}">{{ t.type }}</a></li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>


            <div class="panel-body">
                <ul id="order_list" class="nav nav-pills" data-value="{{ order }}">
                    <li id="test" role="presentation" value="year" data-value="year"><a>年份</a></li>
                    <li role="presentation" value="avg_rating" data-value="avg_rating"><a>得分</a></li>
                    <li role="presentation" value="total_rating" data-value="total_rating"><a>总排行</a></li>
                    <li role="presentation" value="month_rating" data-value="month_rating"><a>月排行</a></li>
                    <li role="presentation" value="week_rating" data-value="week_rating"><a>月排行</a></li>
                </ul>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">分类：魔幻</div>
            <div class="panel-body">
                <div class="row">
                    {% for drama in object_list %}
                        <div class="col-sm-6 col-md-6">
                            <div class="col-md-4">
                                <a href="{% url 'dramas:drama_detail' drama.id %}">
                                    <img src="{{ drama.image }}" class="img-thumbnail" alt="{{ drama.title_cn }}" style="height: 210px;width: 140px">
                                </a>
                            </div>
                            <div class="col-md-8">
                                <h4>
                                    <mark><a href="{% url 'dramas:drama_detail' drama.id %}">{{ drama.title_cn }}</a></mark>
                                </h4>
                                <p>
                                    <span>原名:</span><span>{{ drama.title_en }}</span>
                                </p>
                                <p>
                                    <span>又名:</span><span>{{ drama.alternate_name }}</span>
                                </p>
                                <p>
                                    <span>年份:</span><span>{{ drama.year }}</span>
                                </p>
                                <p>
                                    <span>分类:</span>
                                    <span>
                                        {% for drama_type in drama.types.all %}
                                            {{ drama_type.type }}
                                        {% endfor %}
                                    </span>
                                </p>
                                <p>
                                    <span>评分:</span><span>{{ drama.avg_rating }}</span>
                                </p>
                                <p>
                                    <span>集数:</span><span>{{ drama.episodes }}</span>
                                </p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        <!-- 分页 -->
        <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="pagination">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                {% if page_args_str%}
                                    <a href="?page={{ page_obj.previous_page_number }}{{ page_args_str }}">上一页</a>
                                {% else %}
                                    <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
                                {% endif %}
                            {% endif %}

                            <span class="current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>

                            {% if page_obj.has_next %}
                                {% if page_args_str%}
                                    <a href="?page={{ page_obj.next_page_number }}{{ page_args_str }}">下一页</a>
                                {% else %}
                                    <a href="?page={{ page_obj.next_page_number }}">下一页</a>
                                {% endif %}
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>
    </div>
{% endblock %}

{% block js %}
<script type="text/javascript">
    var type_id = $('#type_list').attr('data-value')
    var cur_order = $('#order_list').attr('data-value')
    var orderLis = $('#order_list li')
    if(type_id && cur_order) {
        for(var i = 0; i < orderLis.length; i++) {
            var node_order = $(orderLis[i]).attr('data-value')
            $(orderLis[i]).find("a").attr('href', '/dramas/category?type=' + type_id + '&order=' + node_order)
            if(cur_order == node_order) {
                $(orderLis[i]).addClass('active')
            }
        }
    } else if(type_id) {
        $(orderLis[0]).addClass('active')
        for(var i = 0; i < orderLis.length; i++) {
            $(orderLis[i]).find("a").attr('href', '/dramas/category?type=' + type_id + '&order=' + $(orderLis[i]).attr('data-value'))
        }
    } else if(cur_order){
        for(var i = 0; i < orderLis.length; i++) {
            var node_order = $(orderLis[i]).attr('data-value')
            $(orderLis[i]).find("a").attr('href', '/dramas/category?order=' + node_order)
            if(cur_order == node_order) {
                $(orderLis[i]).addClass('active')
            }
        }
    } else {
        $(orderLis[0]).addClass('active')
        for(var i = 0; i < orderLis.length; i++) {
            var node_order = $(orderLis[i]).attr('value')
            $(orderLis[i]).find("a").attr('href', '/dramas/category?order=' + node_order)
        }
    }
</script>
{% endblock %}

templates/home/index.html
{% extends "base.html" %}

{% load static %}

{% block title %}首页{% endblock %}

{% block css %}

{% endblock %}

{% block content %}

    <div class="jumbotron" style="background-image: url('{% static 'home/img/bg_index.jpg' %}')">
        <div class="container">
            <form class="form-horizontal" onsubmit="return false;">
                <div class="form-group-lg col-md-6 col-md-offset-3 has-feedback">
                    <input id="searchInput" type="text" class="form-control" placeholder="搜索你想要的美剧">
                    <span id="searchButton" class="glyphicon glyphicon-search form-control-feedback span-button" aria-hidden="true"></span>
                </div>
            </form>
        </div>
    </div>

    <div class="container">
        <div>
            <div class="row">
                <div class="col-md-11">
                    <h2><b>科幻/魔幻</b></h2>
                </div>
            </div>
            <div class="row hr"></div>
            <div class="row">
                <div class="col-md-offset-1 col-md-6 index-category">
                    {% for d in sci_magic_new_dramas %}
                        <div class="col-md-4">
                            <div>
                                <a href="{% url 'dramas:drama_detail' d.id %}">
                                    <img src="{{ d.image }}">
                                </a>
                                <div class="caption text-center">
                                    <h5><a href="{% url 'dramas:drama_detail' d.id %}">{{ d.title_cn }}</a></h5>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <div class="col-md-4">
                    <span class="list-group-item list-group-item-info">科幻/魔幻总榜前10</span>
                    {% for d in sci_magic_top10_dramas %}
                        <a href="{% url 'dramas:drama_detail' d.id %}" class="list-group-item">{{ forloop.counter }}  {{ d.title_cn }}     {{ d.avg_rating }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div>
            <div class="row">
                <div class="col-md-12">
                    <h2><b>灵异/惊悚</b></h2>
                </div>
            </div>
            <div class="row hr"></div>
            <div class="row">
                <div class="col-md-offset-1 col-md-6 index-category">
                    {% for d in supernatural_scary_new_dramas %}
                        <div class="col-md-4">
                            <div>
                                <a href="{% url 'dramas:drama_detail' d.id %}">
                                    <img src="{{ d.image }}">
                                </a>
                                <div class="caption text-center">
                                    <h5><a href="{% url 'dramas:drama_detail' d.id %}">{{ d.title_cn }}</a></h5>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <div class="col-md-4">
                    <span class="list-group-item list-group-item-info">灵异/惊悚总榜前10</span>
                    {% for d in supernatural_scary_top10_dramas %}
                        <a href="{% url 'dramas:drama_detail' d.id %}" class="list-group-item">{{ forloop.counter }}  {{ d.title_cn }}     {{ d.avg_rating }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div>
            <div class="row">
                <div class="col-md-12">
                    <h2><b>都市/情感</b></h2>
                </div>
            </div>
            <div class="row hr"></div>
            <div class="row">
                <div class="col-md-offset-1 col-md-6 index-category">
                    {% for d in urban_emotional_new_dramas %}
                        <div class="col-md-4">
                            <div>
                                <a href="{% url 'dramas:drama_detail' d.id %}">
                                    <img src="{{ d.image }}">
                                </a>
                                <div class="caption text-center">
                                    <h5><a href="{% url 'dramas:drama_detail' d.id %}">{{ d.title_cn }}</a></h5>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <div class="col-md-4">
                    <span class="list-group-item list-group-item-info">都市/情感总榜前10</span>
                    {% for d in urban_emotional_top10_dramas %}
                        <a href="{% url 'dramas:drama_detail' d.id %}" class="list-group-item">{{ forloop.counter }}  {{ d.title_cn }}     {{ d.avg_rating }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div>
            <div class="row">
                <div class="col-md-12">
                    <h2><b>犯罪/历史</b></h2>
                </div>
            </div>
            <div class="row hr"></div>
            <div class="row">
                <div class="col-md-offset-1 col-md-6 index-category">
                    {% for d in crime_historic_new_dramas %}
                        <div class="col-md-4">
                            <div>
                                <a href="{% url 'dramas:drama_detail' d.id %}">
                                    <img src="{{ d.image }}">
                                </a>
                                <div class="caption text-center">
                                    <h5><a href="{% url 'dramas:drama_detail' d.id %}">{{ d.title_cn }}</a></h5>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <div class="col-md-4">
                    <span class="list-group-item list-group-item-info">犯罪/历史总榜前10</span>
                    {% for d in crime_historic_top10_dramas %}
                        <a href="{% url 'dramas:drama_detail' d.id %}" class="list-group-item">{{ forloop.counter }}  {{ d.title_cn }}     {{ d.avg_rating }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block js %}
    <script type="text/javascript">
        $('#searchButton').click(submit_search)
    
        function submit_search() {
            var search_text = $('#searchInput').val()
            if(search_text) {
                window.location.href = "/dramas/search/wd=" + search_text
            }
        }
        
        $('#searchInput').keydown(function (event) {
            var e = event || window.event || arguments.callee.caller.arguments[0];

            if(e && e.keyCode==13){ // enter 键
                 submit_search()
            }
        })
    </script>
{% endblock %}

templates/home/search.html
{% extends "base.html" %}

{% block title %}搜索结果:{{ search_text }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>关于“{{ search_text }}”的搜索结果(全部共<mark>{{ paginator.count }}</mark>条)</h2>
            </div>
        </div>

        <!-- 搜索结果开始 -->
        <div>
            {% for drama in object_list %}
                <div class="row">
                    <p class="hr-dot"></p>
                    <div class="col-md-9">
                        <div class="col-md-2">
                            <a href="{% url 'dramas:drama_detail' drama.id %}">
                                <img src="{{ drama.image }}" alt="{{ drama.title_cn }}" style="height: 150px; width: 100px;">
                            </a>
                        </div>
                        <div class="col-md-10">
                            <mark><a href="{% url 'dramas:drama_detail' drama.id %}">{{ drama.title_cn }}/ {{ drama.alternate_name }} / {{ drama.title_en }}</a></mark>
                            <div>
                                <span>
                                    {% for director in drama.director_set.all %}{{ director.name }} /{% endfor %}
                                    {% for cast in drama.cast_set.all %}{{ cast.name }} / {% endfor %}
                                </span>
                            </div>

                            <div>
                                {% load my_tag %}
                                {% divide drama.avg_rating 2 as stars %}
                                <span class="review-list-rating">
                                    {% for i in stars|times %}
                                        <i class="glyphicon glyphicon-star"></i>
                                    {% endfor %}
                                </span>
                                <span>{{ drama.avg_rating }}</span>
                                <span>（<a href="{% url 'reviews:review_list' drama.id %}">{{ drama.reviews.count }}人评价</a>）</span>
                            </div>
                            <p>{{ drama.summary|truncatechars:150 }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <!-- 分页 -->
        <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="pagination">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
                            {% endif %}

                            <span class="current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>

                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}">下一页</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>
    </div>

{% endblock %}

templates/home/sign_up.html
{% extends "base.html" %}

{% load static %}

{% block title %}首页{% endblock %}

{% block css %}

{% endblock %}

{% block content %}

{% if form.errors %}
    <p>
        <strong>{{ form.errors }}</strong>
    </p>
{% endif %}

<div class="container">
    <div class="panel panel-default sign-panel">
        <div class="panel-body">
            <form class="form-horizontal" action="{% url 'accounts:sign_up' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="emailInput" class="col-sm-3 control-label">Email</label>
                    <div class="col-sm-6">
                        <input type="email" class="form-control" id="emailInput" placeholder="jackbauer@gmail.com"  name="email">
                    </div>
                </div>
                <div class="form-group">
                    <label for="passwordInput1" class="col-sm-3 control-label">Password</label>
                    <div class="col-sm-6">
                        <input type="password" class="form-control" id="passwordInput1" name="password1">
                    </div>
                </div>
                <div class="form-group">
                    <label for="passwordInput2" class="col-sm-3 control-label">Password confirmation</label>
                    <div class="col-sm-6">
                        <input type="password" class="form-control" id="passwordInput2" name="password2">
                    </div>
                </div>
                <div class="form-group">
                    <label for="nicknameInput" class="col-sm-3 control-label">Nickname</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" id="nicknameInput" name="nickname">
                    </div>
                </div>
                <div class="form-group">
                    <label for="cityInput" class="col-sm-3 control-label">City</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" id="cityInput" name="city">
                    </div>
                </div>
                <div class="form-group">
                    <label for="dateOfBirthInput" class="col-sm-3 control-label">Birthday</label>
                    <div class="col-sm-6">
                        <input type="date" class="form-control" id="dateOfBirthInput" name="date_of_birth">
                    </div>
                </div>
                <div class="form-group">
                    <label for="sexInput" class="col-sm-3 control-label">Sex</label>
                    <div class="col-sm-6">
                        <select class="form-control" name="sex">
                            {% for sex in sexes %}
                                <option value="{{ sex|first }}">{{ sex|last }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-3 col-sm-6">
                        <button type="submit" class="btn btn-default">sign up</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}