home/urls.py
from django.conf.urls import url

from accounts.views import user_view
from home.views import basic_view

app_name = 'home'

urlpatterns = [
    # ex: /polls/
    url(r'^$', basic_view.to_index, name='index_root'),
    url(r'^index$', basic_view.to_index, name='index'),
]

space/urls.py
from django.conf.urls import url

from space.views import follower_view
from space.views import following_view
from space.views import search_view
from space.views import space_view

app_name = 'space'

urlpatterns = [
    url(r'^space/$', space_view.SpaceView.as_view(), name='index_without_id'),
    url(r'^space/(?P<user_id>[0-9]+)/$', space_view.SpaceView.as_view(), name='index_with_id'),
    url(r'^space/(?P<user_id>[0-9]+)/following/$', following_view.FollowingView.as_view(), name='space_following'),
    url(r'^space/add_following/$', following_view.AddFollowingView.as_view(), name='add_following'),
    url(r'^space/cancel_following/$', following_view.DeleteFollowingView.as_view(), name='cancel_following'),
    url(r'^space/search/wd=(?P<search_text>.+)/$', search_view.PeopleSearchView.as_view(), name='search_people'),
    url(r'^space/(?P<user_id>[0-9]+)/follower/$', follower_view.FollowerView.as_view(), name='space_follower'),
]

tv_drama_resys/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# Create a router and register our viewsets with it.
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter
from rest_framework.urlpatterns import format_suffix_patterns

from accounts.views.user_view import UserViewSet
from meiju.views.drama_view import DramaViewSet

# router = DefaultRouter()
# router.register(r'dramas', DramaViewSet)
# router.register(r'users', UserViewSet)

# The API URLs are now determined automatically by the router.
# Additionally, we include the login URLs for the browsable API.


urlpatterns = [
    # url(r'^', include(router.urls)),
    # url('^', include('django.contrib.auth.urls')),
    url(r'^about/$', TemplateView.as_view(template_name="about.html")),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls')),
    url(r'^', include('meiju.urls')),
    url(r'^', include('reviews.urls')),
    url(r'^', include('space.urls')),
    url(r'^', include('home.urls')),
    url(r'^', include('data_visualization.urls')),
]

urlpatterns = format_suffix_patterns(urlpatterns)

space/views/follower_view.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from accounts.entities.follower import Follower
from accounts.models import MyUser


class FollowerView(LoginRequiredMixin, ListView):
    template_name = 'space/follower.html'
    paginate_by = settings.OBJECTS_NUM_PER_PAGE

    def get_queryset(self):
        request = self.request
        user_id = int(self.kwargs['user_id'])
        if request.user.is_authenticated and user_id == request.user.id:
            check_user = request.user
        else:
            check_user = MyUser.objects.get(pk=user_id)

        self.queryset = Follower.objects.filter(user=check_user)
        self.kwargs['check_user'] = check_user
        return super(FollowerView, self).get_queryset()

    def render_to_response(self, context, **response_kwargs):
        followings = self.request.user.followings.all()
        following_arr = []
        for f in followings:
            following_arr.append(f.following_id)
        context['followings'] = following_arr

        context['check_user'] = self.kwargs['check_user']
        
        return super(FollowerView, self).render_to_response(context, **response_kwargs)

space/views/following_view.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView

from accounts.entities.follower import Follower
from accounts.entities.following import Following
from accounts.models import MyUser


def to_following(request):
    return render(request, 'space/following.html')


class FollowingView(LoginRequiredMixin, ListView):
    template_name = 'space/following.html'
    paginate_by = settings.OBJECTS_NUM_PER_PAGE

    def get_queryset(self):
        request = self.request
        user_id = int(self.kwargs['user_id'])
        if request.user.is_authenticated and user_id == request.user.id:
            check_user = request.user
        else:
            check_user = MyUser.objects.get(pk=user_id)

        self.queryset = Following.objects.filter(user=check_user)
        self.kwargs['check_user'] = check_user
        return super(FollowingView, self).get_queryset()

    def get_context_data(self, **kwargs):
        return super(FollowingView, self).get_context_data(check_user=self.kwargs['check_user'])


class AddFollowingView(View):
    def post(self, request, *args, **kwargs):
        if self.request.is_ajax():
            following_id = int(request.POST['following_id'])
            following_qset = MyUser.objects.filter(pk=following_id)
            if following_qset.exists():
                following_user = following_qset.get()
                following = Following()
                following.user = self.request.user
                following.following = following_user
                following.save()

                follower = Follower()
                follower.user = following_user
                follower.follower = self.request.user
                follower.save()

                data = {
                    'msg': '关注成功！',
                }
                return JsonResponse(data)

        raise Http404("Drama does not exist")


class DeleteFollowingView(View):
    def post(self, request, *args, **kwargs):
        if self.request.is_ajax():
            following_id = int(request.POST['fid'])
            user_id = request.user.id
            Following.objects.filter(following_id=following_id, user_id=user_id).delete()
            Follower.objects.filter(follower_id=user_id, user_id=following_id).delete()

            data = {
                'msg': '取消关注成功！',
            }
            return JsonResponse(data)

        raise Http404("Drama does not exist")

space/views/search_view.py
from django.conf import settings
from django.db.models import Q
from django.views.generic import ListView

from accounts.models import MyUser


class PeopleSearchView(ListView):
    template_name = 'space/people_search.html'
    paginate_by = settings.OBJECTS_NUM_PER_PAGE

    def get_queryset(self):
        key = self.kwargs['search_text']
        self.queryset = MyUser.objects.filter(
            (Q(nickname__contains=key) | Q(email__contains=key)) &
            Q(is_admin=False)
        ).exclude(id=self.request.user.id).order_by('-date_joined')

        return super(PeopleSearchView, self).get_queryset()

    def render_to_response(self, context, **response_kwargs):
        followings = self.request.user.followings.all()
        following_arr = []
        for f in followings:
            following_arr.append(f.following_id)
        context['followings'] = following_arr

        context['search_text'] = self.kwargs['search_text']

        return super(PeopleSearchView, self).render_to_response(context, **response_kwargs)

space/views/space_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views.generic import TemplateView

from accounts.models import MyUser


class SpaceView(LoginRequiredMixin, TemplateView):
    template_name = 'space/space.html'

    def get_context_data(self, **kwargs):
        request = self.request

        if 'user_id' in self.kwargs:
            user_id = int(self.kwargs['user_id'])
        else:
            user_id = request.user.id

        if user_id == request.user.id:
            check_user = request.user
        else:
            check_user = MyUser.objects.get(pk=user_id)
            kwargs['followed'] = True if request.user.followings.filter(following=check_user).exists() else False

        kwargs['check_user'] = check_user
        kwargs['hot_reviews'] = check_user.reviews.exclude(Q(title='') | Q(title=None))[0:2]
        kwargs['watched_reviews'] = check_user.reviews.filter(is_watched=True)
        kwargs['unwatched_reviews'] = check_user.reviews.filter(is_watched=False)
        kwargs['recent_review_likes'] = check_user.review_likes.order_by('like_time')[0:2]
        kwargs['sexes'] = MyUser.SEX_CHOICES
        return super(SpaceView, self).get_context_data(**kwargs)

# If the user isn’t logged in, redirect to settings.LOGIN_URL,
# passing the current absolute path in the query string.
# @login_required
# def to_space(request):
# if not request.user.is_authenticated:
#     return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
# return render(request, 'space/space.html')


# @permission_required('polls.can_vote', raise_exception=True)
# def my_view(request):
#     ...

templates/space/follower.html
{% extends 'base.html' %}

{% load static %}
{% load my_tag %}

{% block title %}
    {% if check_user == user %}
        关注我的人
    {% else %}
        关注{{ check_user.nickname }}的人
    {% endif %}
{% endblock %}

{% block css %}
{% endblock %}

{% block content %}
    <div class="container">
        {% csrf_token %}
        <div class="row">
            {% if check_user == user %}
                <h2>关注我的人({{ paginator.count }})</h2>
            {% else %}
                <h2>关注{{ check_user.nickname }}的人({{ paginator.count }})</h2>
            {% endif %}
        </div>

        <div>
            {% for f in object_list %}
                <div class="row">
                    <div class="col-md-1">
                        <a href="{% url 'space:index_with_id' f.follower_id %}">
                            <img src="https://img3.doubanio.com/icon/u155403369-3.jpg">
                        </a>
                    </div>
                    <div class="col-md-8 space-follower-user-info">
                        <div class="col-md-10">
                            <p>
                                <a href="{% url 'space:index_with_id' f.follower_id%}">
                                    <mark>{{ f.follower.nickname }}</mark>
                                </a>
                            </p>
                            <span>签名：{% if f.follower.introduction %}{{ f.follower.introduction }}{% endif %}</span>
                        </div>

                        {% if f.follower_id in followings %}
                            <div class="col-md-2 space-following-cancel">
                                <span class="span-button" data-following="{{ f.follower_id }}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> 取消关注</span>
                            </div>
                        {% else %}
                            <div class="col-md-2">
                                <a class="following_btn" role="button" data-value="{{ f.follower_id }}">
                                    <span><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> 添加关注</span>
                                </a>
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-md-9 hr"></div>
                </div>
            {% endfor %}
        </div>

        <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="pagination">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
                            {% endif %}

                            <span class="current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>

                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}">下一页</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>
    </div>
{% endblock %}

{% block js %}
<script type="text/javascript">
    $(function () {
        $('.space-follower-user-info').each(function (i) {
            var cancel_btn = $(this).find('.span-button')

            $(cancel_btn).click(function () {
                var fid = $(cancel_btn).attr('data-following')
                if(confirm('您确定要取消关注该用户？')) {
                    cancel_following(fid)
                }
            })

            $(this).mouseover(function () {
                $(this).children('.space-following-cancel').show()
            })
            $(this).mouseout(function () {
                $(this).children('.space-following-cancel').hide()
            })
        })
    })

    $(function () {
        $('.space-following-user-info').each(function (i) {
            var cancel_btn = $(this).find('.span-button')

            $(cancel_btn).click(function () {
                var fid = $(cancel_btn).attr('data-following')
                if(confirm('您确定要取消关注该用户？')) {
                    cancel_following(fid)
                }
            })

            $(this).mouseover(function () {
                $(this).children('.space-following-cancel').show()
            })
            $(this).mouseout(function () {
                $(this).children('.space-following-cancel').hide()
            })
        })
    })

    function cancel_following(fid) {
        $.ajax({
            type: "POST",
            url: "{% url 'space:cancel_following' %}",
            data: 'csrfmiddlewaretoken=' + $('input[name=csrfmiddlewaretoken]').val() + '&fid=' + fid,
            dataType: "json",
            success: function (data) {
                history.go(0)
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                alert('服务器错误，请稍后重试！')
            }
        });
    }

    $('.following_btn').click(function () {
        var csrf = $('input[name=csrfmiddlewaretoken]').val();
        var uid = $(this).attr('data-value');
        addFollowing(csrf, uid);
    })

    function addFollowing(csrf, uid) {
        var data = 'csrfmiddlewaretoken=' + csrf + '&following_id=' + uid
        $.ajax({
                 type: "POST",
                 url: "{% url 'space:add_following' %}",
                 data: data,
                 dataType: "json",
                 success: function(data){
                     history.go(0);
                 },
                 error: function(XMLHttpRequest, textStatus, errorThrown) {
                     alert(XMLHttpRequest.status);
                     alert(XMLHttpRequest.readyState);
                     alert(textStatus);
                 }
        });
    }
</script>
{% endblock %}

templates/space/following.html
{% extends 'base.html' %}

{% load static %}
{% load my_tag %}

{% block title %}
    {% if check_user == user %}
        我的关注
    {% else %}
        {{ check_user.nickname }}的关注
    {% endif %}
{% endblock %}

{% block css %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            {% if check_user == user %}
                <h2>我关注的人({{ paginator.count }})</h2>
            {% else %}
                <h2>{{ check_user.nickname }}关注的人({{ paginator.count }})</h2>
            {% endif %}
        </div>

        <div>
            {% for f in object_list %}
                <div class="row">
                    <div class="col-md-1">
                        <a href="{% url 'space:index_with_id' f.following.id %}">
                            <img src="https://img3.doubanio.com/icon/u155403369-3.jpg">
                        </a>
                    </div>

                    <div class="col-md-8 space-following-user-info">
                        <div class="col-md-10">
                            <p>
                                <a href="{% url 'space:index_with_id' f.following.id %}">
                                    <mark>{{ f.following.nickname }}</mark>
                                </a>
                            </p>
                            <span>签名：{% if f.following.introduction %}{{ f.following.introduction }}{% endif %}</span>
                        </div>
                        <div class="col-md-2 space-following-cancel">
                            {% csrf_token %}
                            <span class="span-button" data-following="{{ f.following.id }}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> 取消关注</span>
                        </div>
                    </div>
                    <div class="col-md-9 hr"></div>
                </div>
            {% endfor %}
        </div>

        <!-- 分页 -->
        <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="pagination">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
                            {% endif %}

                            <span class="current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>

                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}">下一页</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>
    </div>
{% endblock %}

{% block js %}
<script type="text/javascript">
    $(function () {
        $('.space-following-user-info').each(function (i) {
            var cancel_btn = $(this).find('.span-button')

            $(cancel_btn).click(function () {
                var fid = $(cancel_btn).attr('data-following')
                if(confirm('您确定要取消关注该用户？')) {
                    cancel_following(fid)
                }
            })

            $(this).mouseover(function () {
                $(this).children('.space-following-cancel').show()
            })
            $(this).mouseout(function () {
                $(this).children('.space-following-cancel').hide()
            })
        })
    })


    function cancel_following(fid) {
        $.ajax({
            type: "POST",
            url: "{% url 'space:cancel_following' %}",
            data: 'csrfmiddlewaretoken=' + $('input[name=csrfmiddlewaretoken]').val() + '&fid=' + fid,
            dataType: "json",
            success: function (data) {
                history.go(0)
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                alert('服务器错误，请稍后重试！')
            }
        });
    }
</script>
{% endblock %}

templates/space/people_search.html
{% extends 'base.html' %}

{% load static %}
{% load my_tag %}

{% block title %}搜索结果为“{{ search_text }}”的人{% endblock %}

{% block css %}
{% endblock %}

{% block content %}
    <div class="container">
        {% csrf_token %}
        <div class="row">
            <h2>搜索“{{ search_text }}”的结果</h2>
        </div>

        <div>
            {% for u in object_list %}
                <div class="row">
                    <div class="col-md-1">
                        <a href="{% url 'space:index_with_id' u.id %}">
                            <img src="https://img3.doubanio.com/icon/u155403369-3.jpg">
                        </a>
                    </div>

                    <div class="col-md-8 space-following-user-info">
                        <div class="col-md-10">
                            <p>
                                <a href="{% url 'space:index_with_id' u.id %}">
                                    <mark>{{ u.nickname }}</mark>
                                </a>
                            </p>
                            <span>签名：{{ u.introduction|noNone }}</span>
                        </div>
                        {% if u.id in followings %}
                            <div class="col-md-2 space-following-cancel">
                                <span class="span-button" data-following="{{ u.id }}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> 取消关注</span>
                            </div>
                        {% else %}
                            <div class="col-md-2">
                                <a class="following_btn" role="button" data-value="{{ u.id }}">
                                    <span><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> 添加关注</span>
                                </a>
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-md-9 hr"></div>
                </div>
            {% endfor %}
        </div>

        <!-- 分页 -->
        <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="pagination">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
                            {% endif %}

                            <span class="current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>

                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}">下一页</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>
    </div>
{% endblock %}

{% block js %}
<script type="text/javascript">
    $(function () {
        $('.space-following-user-info').each(function (i) {
            var cancel_btn = $(this).find('.span-button')

            $(cancel_btn).click(function () {
                var fid = $(cancel_btn).attr('data-following')
                if(confirm('您确定要取消关注该用户？')) {
                    cancel_following(fid)
                }
            })

            $(this).mouseover(function () {
                $(this).children('.space-following-cancel').show()
            })
            $(this).mouseout(function () {
                $(this).children('.space-following-cancel').hide()
            })
        })
    })

    function cancel_following(fid) {
        $.ajax({
            type: "POST",
            url: "{% url 'space:cancel_following' %}",
            data: 'csrfmiddlewaretoken=' + $('input[name=csrfmiddlewaretoken]').val() + '&fid=' + fid,
            dataType: "json",
            success: function (data) {
                history.go(0)
            },
            error: function (XMLHttpRequest, textStatus, errorThrown) {
                alert('服务器错误，请稍后重试！')
            }
        });
    }


    $('.following_btn').click(function () {
        var csrf = $('input[name=csrfmiddlewaretoken]').val();
        var uid = $(this).attr('data-value');
        addFollowing(csrf, uid);
    })

    function addFollowing(csrf, uid) {
        var data = 'csrfmiddlewaretoken=' + csrf + '&following_id=' + uid
        $.ajax({
                 type: "POST",
                 url: "{% url 'space:add_following' %}",
                 data: data,
                 dataType: "json",
                 success: function(data){
                     history.go(0);
                 },
                 error: function(XMLHttpRequest, textStatus, errorThrown) {
                     alert(XMLHttpRequest.status);
                     alert(XMLHttpRequest.readyState);
                     alert(textStatus);
                 }
        });
    }
</script>
{% endblock %}