accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views

from accounts.views import login_view
from accounts.views import password_change_view
from accounts.views import sign_up_view
from accounts.views import user_change_view
from accounts.views.user_view import UserViewSet

app_name = 'accounts'

user_list = UserViewSet.as_view({
    'get': 'list'
})
user_detail = UserViewSet.as_view({
    'get': 'retrieve'
})

urlpatterns = [
    url(r'^accounts/modify$', user_change_view.UserChangeView.as_view(), name='change_user'),
    url(r'^accounts/changepassword/$', password_change_view.PasswordChangeView.as_view(), name='change_password'),
    url(r'^join/$', sign_up_view.SignUpView.as_view(), name='sign_up'),
    url(r'^login/$', login_view.LoginView.as_view(), name='log_in'),
    url(r'^logout/$', views.LogoutView.as_view(), name='log_out'),
    url(r'^users/$', user_list, name='user-list'),
    url(r'^users/(?P<pk>[0-9]+)/$', user_detail, name='user-detail')
]

# urlpatterns = [
#     url(r'^users/$', user_view.UserList.as_view(), name='user-list'),
#     url(r'^users/(?P<pk>[0-9]+)/$', user_view.UserDetail.as_view(), name='user-detail'),
# ]

# urlpatterns = format_suffix_patterns(urlpatterns)

data_visualization/urls.py
from django.conf.urls import url

from data_visualization import views

app_name = 'data_visualization'

urlpatterns = [
    url(r'^visual/$', views.visual, name='visual'),
    url(r'^visual/getSexs$', views.getSexs, name='get_sexs'),
]

home/urls.py
from django.conf.urls import url

from accounts.views import user_view
from home.views import basic_view

app_name = 'home'

urlpatterns = [
    # ex: /polls/
    url(r'^$', basic_view.to_index, name='index_root'),
    url(r'^index$', basic_view.to_index, name='index'),
]

meiju/urls.py
from django.conf.urls import url
from meiju.views import drama_view
from rest_framework.urlpatterns import format_suffix_patterns

from meiju.views import tv_drama_view
from meiju.views.drama_view import DramaViewSet, DramaTypeViewSet

app_name = 'dramas'

drama_list = DramaViewSet.as_view({
    'get': 'list'
})
drama_detail = DramaViewSet.as_view({
    'get': 'retrieve'
})
type_list = DramaTypeViewSet.as_view({
    'get': 'list'
})

urlpatterns = [
    # url(r'^dramas/category/type=(?P<type>.+)/$', tv_drama_view.CategoryDramaView.as_view(), name='drama_category'),
    url(r'^dramas/category/$', tv_drama_view.CategoryDramaView.as_view(), name='drama_category'),
    url(r'^dramas/search/wd=(?P<search_text>.+)/$', tv_drama_view.SearchDramaView.as_view(), name='search_drama'),
    url(r'^dramas/(?P<pk>[0-9]+)/$', tv_drama_view.DramaDetailView.as_view(), name='drama_detail'),
    url(r'^dramas/$', drama_list, name='drama-list'),
    url(r'^drama_type/$', type_list, name='drama-type-list')
]


# urlpatterns = [
#     url(r'^dramas/$', drama_view.DramaList.as_view(), name='drama-list'),
#     url(r'^dramas/(?P<pk>[0-9]+)/$', drama_view.DramaDetail.as_view(), name='drama-detail'),
# ]

# urlpatterns = format_suffix_patterns(urlpatterns)

space/urls.py
from django.conf.urls import url

from space.views import follower_view
from space.views import following_view
from space.views import search_view
from space.views import space_view

app_name = 'space'

urlpatterns = [
    url(r'^space/$', space_view.SpaceView.as_view(), name='index_without_id'),
    url(r'^space/(?P<user_id>[0-9]+)/$', space_view.SpaceView.as_view(), name='index_with_id'),
    url(r'^space/(?P<user_id>[0-9]+)/following/$', following_view.FollowingView.as_view(), name='space_following'),
    url(r'^space/add_following/$', following_view.AddFollowingView.as_view(), name='add_following'),
    url(r'^space/cancel_following/$', following_view.DeleteFollowingView.as_view(), name='cancel_following'),
    url(r'^space/search/wd=(?P<search_text>.+)/$', search_view.PeopleSearchView.as_view(), name='search_people'),
    url(r'^space/(?P<user_id>[0-9]+)/follower/$', follower_view.FollowerView.as_view(), name='space_follower'),
]

tv_drama_resys/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# Create a router and register our viewsets with it.
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter
from rest_framework.urlpatterns import format_suffix_patterns

from accounts.views.user_view import UserViewSet
from meiju.views.drama_view import DramaViewSet

# router = DefaultRouter()
# router.register(r'dramas', DramaViewSet)
# router.register(r'users', UserViewSet)

# The API URLs are now determined automatically by the router.
# Additionally, we include the login URLs for the browsable API.


urlpatterns = [
    # url(r'^', include(router.urls)),
    # url('^', include('django.contrib.auth.urls')),
    url(r'^about/$', TemplateView.as_view(template_name="about.html")),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls')),
    url(r'^', include('meiju.urls')),
    url(r'^', include('reviews.urls')),
    url(r'^', include('space.urls')),
    url(r'^', include('home.urls')),
    url(r'^', include('data_visualization.urls')),
]

urlpatterns = format_suffix_patterns(urlpatterns)

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>关于我们</title>

    <style type="text/css">
        body {
            padding: 0;
            margin: 0;
        }
        .bg1 {
            width:200px;
            height: 200px;
            background-color: #fde16d;
            top: 20px;
            left: 20px;
            position: relative;
        }

        .bg1 div {
            width: 100px;
            height: 100px;
            background-color: #843534;
            top: 20px;
            left: 20px;
            position: absolute;
        }

        .bg2 {
            width:200px;
            height: 200px;
            background-color: cornflowerblue;
            top: 20px;
            left: 20px;
            position: relative;
        }
    </style>

</head>
<body>
    <h1>我们是傻逼，不用关注我们~</h1>

<div class="bg1">
    <div></div>
</div>

<div class="bg2"></div>

</body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>{% block title %}My amazing site{% endblock %}</title>
    {% include 'commom_css_block.html' %}
    {% block css %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">TV Drama</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'home:index_root' %}">首页 <span class="sr-only">(current)</span></a>
                    </li>
                    <li><a href="{% url 'dramas:drama_category' %}">分类查询</a></li>
                    {% if user.is_admin %}
                    <li><a href="{% url 'data_visualization:visual' %}">数据可视化</a></li>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'space:index_with_id' user.id %}">我的空间</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:log_in' %}">我的空间</a></li>
                    {% endif %}
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">{{ user.nickname }}<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url 'accounts:change_password' %}">修改密码</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{% url 'accounts:log_out' %}">退出</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{% url 'accounts:sign_up' %}">注册</a></li>
                        <li><a href="{% url 'accounts:log_in' %}">登录</a></li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

    <div id="content">
        {% block content %}{% endblock %}
    </div>

    <footer class="footer">
      <p>Follow me via Sina Weibo - <a href="http://weibo.com/u/1910465675">@HiJackBauer</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>

{% include 'common_js_block.html' %}
{% block js %}{% endblock %}
</body>
</html>

templates/commom_css_block.html
{% load static %}

<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'home/style.css' %}" />

templates/common_js_block.html
{% load static %}

<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>