home/urls.py
from django.conf.urls import url

from accounts.views import user_view
from home.views import basic_view

app_name = 'home'

urlpatterns = [
    # ex: /polls/
    url(r'^$', basic_view.to_index, name='index_root'),
    url(r'^index$', basic_view.to_index, name='index'),
]

reviews/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns

from reviews.views import review_comment_view
from reviews.views import review_like_view
from reviews.views import review_view
from reviews.views.review_view import ReviewViewSet

app_name = 'reviews'

review_list = ReviewViewSet.as_view({
    'get': 'list',
    'post': 'create'
})
review_detail = ReviewViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})

urlpatterns = [
    url(r'^dramas/(?P<pk>[0-9]+)/review/$', review_view.ReviewListView.as_view(), name='review_list'),
    url(r'^reviews/add_review/$', review_view.AddReviewView.as_view(), name='add_review'),
    url(r'^reviews/add_review_comment/$', review_comment_view.AddReviewCommentView.as_view(), name='add_review_comment'),
    url(r'^reviews/add_review_likes/$', review_like_view.AddReviewLikesView.as_view(), name='add_review_likes'),
    url(r'^reviews/delete_review/$', review_view.DeleteReviewView.as_view(), name='delete_review'),
    url(r'^reviews/unwatch_review/$', review_view.AddUnwatchedReviewView.as_view(), name='unwatch_review'),
    url(r'^reviews/delete_review_likes/$', review_like_view.DeleteReviewLikesView.as_view(), name='delete_review_likes'),
    url(r'^reviews/(?P<pk>[0-9]+)/$', review_comment_view.ReviewCommentView.as_view(), name='review_detail'),

    # url(r'^reviews/$', review_list, name='review-list'),
    # url(r'^reviews/(?P<pk>[0-9]+)/$', review_detail, name='review-detail'),
    # url(r'^review-comments/$', review_comment_view.ReviewCommentList.as_view(), name='review-comment-list'),
    # url(r'^review-comments/(?P<pk>[0-9]+)/$', review_comment_view.ReviewCommentDetail.as_view(), name='review-comment-detail'),
]

tv_drama_resys/urls.py
from django.conf.urls import url, include
from django.contrib import admin

# Create a router and register our viewsets with it.
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter
from rest_framework.urlpatterns import format_suffix_patterns

from accounts.views.user_view import UserViewSet
from meiju.views.drama_view import DramaViewSet

# router = DefaultRouter()
# router.register(r'dramas', DramaViewSet)
# router.register(r'users', UserViewSet)

# The API URLs are now determined automatically by the router.
# Additionally, we include the login URLs for the browsable API.


urlpatterns = [
    # url(r'^', include(router.urls)),
    # url('^', include('django.contrib.auth.urls')),
    url(r'^about/$', TemplateView.as_view(template_name="about.html")),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls')),
    url(r'^', include('meiju.urls')),
    url(r'^', include('reviews.urls')),
    url(r'^', include('space.urls')),
    url(r'^', include('home.urls')),
    url(r'^', include('data_visualization.urls')),
]

urlpatterns = format_suffix_patterns(urlpatterns)

meiju/models/drama.py
from django.db import models

from meiju.models.drama_type import DramaType


class Drama(models.Model):
    title_cn = models.CharField(max_length=200, null=True, blank=True)
    image = models.URLField()
    title_en = models.CharField(max_length=200)
    # duration = models.PositiveSmallIntegerField()
    year = models.PositiveSmallIntegerField()
    episodes = models.PositiveSmallIntegerField()
    summary = models.TextField(blank=True, null=True)
    types = models.ManyToManyField(DramaType, related_name='types')
    douban_url = models.URLField(null=True, blank=True)
    seasons_count = models.PositiveSmallIntegerField(default=1)
    current_season = models.PositiveSmallIntegerField(default=1)
    alternate_name = models.CharField(max_length=200, null=True, blank=True)
    avg_rating = models.DecimalField(default=0, max_digits=8, decimal_places=1)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title_en

    # class Meta:
    #     ordering = ('created',)

meiju/models/drama_type.py
from django.db import models


class DramaType(models.Model):
    type = models.CharField(max_length=200, unique=True)

    class Meta:
        db_table = 'meiju_type'

    def __str__(self):
        return self.type

meiju/views/drama_view.py
from rest_framework import viewsets
from meiju.models.drama import Drama
from meiju.models.drama_type import DramaType
from meiju.serializers.drama_serializer import DramaSerializer
from meiju.serializers.drama_type_serializer import DramaTypeSerializer


class DramaViewSet(viewsets.ReadOnlyModelViewSet):
    """
    This viewset automatically provides `list` and `detail` actions.
    """
    queryset = Drama.objects.all()
    serializer_class = DramaSerializer


class DramaTypeViewSet(viewsets.ReadOnlyModelViewSet):
    """
    This viewset automatically provides `list` and `detail` actions.
    """
    queryset = DramaType.objects.all()
    serializer_class = DramaTypeSerializer


"""
class DramaList(generics.ListCreateAPIView):
    queryset = Drama.objects.all()
    serializer_class = DramaSerializer


class DramaDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Drama.objects.all()
    serializer_class = DramaSerializer
"""

"""
class DramaList(mixins.ListModelMixin,
                mixins.CreateModelMixin,
                generics.GenericAPIView):
    queryset = Drama.objects.all()
    serializer_class = DramaSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)


class DramaDetail(mixins.RetrieveModelMixin,
                    mixins.UpdateModelMixin,
                    mixins.DestroyModelMixin,
                    generics.GenericAPIView):
    queryset = Drama.objects.all()
    serializer_class = DramaSerializer

    def get(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)
"""

"""
class DramaList(APIView):
    def get(self, request, format=None):
        dramas = Drama.objects.all()
        serializer = DramaSerializer(dramas, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = DramaSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class DramaDetail(APIView):

    def get_object(self, pk):
        try:
            return Drama.objects.get(pk=pk)
        except Drama.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        drama = self.get_object(pk)
        serializer = DramaSerializer(drama)
        return Response(serializer.data)

    def put(self, request, pk, format=None):
        drama = self.get_object(pk)
        serializer = DramaSerializer(drama, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        drama = self.get_object(pk)
        drama.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
"""

"""
@api_view(['GET', 'POST'])
def drama_list(request, format=None):
    if request.method == 'GET':
        dramas = Drama.objects.all()
        serializer = DramaSerializer(dramas, many=True)
        return Response(serializer.data)

    elif request.method == 'POST':
        serializer = DramaSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET', 'PUT', 'DELETE'])
def drama_detail(request, pk, format=None):

    try:
        drama = Drama.objects.get(pk=pk)
    except Drama.DoesNotExist:
        return Response(status=status.HTTP_404_NOT_FOUND)

    if request.method == 'GET':
        serializer = DramaSerializer(drama)
        return Response(serializer.data)

    elif request.method == 'PUT':
        serializer = DramaSerializer(drama, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    elif request.method == 'DELETE':
        drama.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

"""

templates/drama/review_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{ review.title }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>{{ review.title }}</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-md-9 review-list-user-info">
                <img src="https://img3.doubanio.com/icon/u39561667-4.jpg"/>
                <span>{{ review.user.nickname }}</span>
                {% load my_tag %}
                {% divide review.rating 2 as stars %}
                    <span class="review-list-rating" data-value="{{ review.rating }}">
                        {% for i in stars|times %}
                            <i class="glyphicon glyphicon-star"></i>
                        {% endfor %}
                    </span>
                <span>{{ review.pubtime }}</span>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-md-9">
                <p>{{ review.content }}
                    <mark><a href="#">共{{ review.review_comments.count }}回应</a></mark>
                </p>
            </div>
        </div>

        <!-- 点赞 -->
        <div class="row">
            <div class="col-xs-12 col-md-9">
                <form id="review_likes_form" method="post" class="center-block">
                    {% csrf_token %}
                    {% if review_like %}
                        <input type="hidden" name="pk" value="{{ review_like.id }}">
                        <a class="btn btn-default btn-lg active" role="button" onclick="submit_review_likes(false)">
                            <span class="glyphicon glyphicon-thumbs-up"></span>
                            <span>{{ review.review_likes.count }}</span>
                        </a>
                    {% else %}
                        <input type="hidden" name="review" value="{{ review.id }}">
                        <a class="btn btn-default btn-lg" role="button" onclick="submit_review_likes(true)">
                            <span class="glyphicon glyphicon-thumbs-up"></span>
                            <span>{{ review.review_likes.count }}</span>
                        </a>
                    {% endif %}
                </form>
            </div>
        </div>

        <div class="row">
            <div class="col-md-9 hr"></div>
        </div>

        <!-- users' comments of this review -->
        <div class="user-review-comment">
            {% for review_comment in reviewcomment_list %}
                <div class="row">
                    <div class="col-md-1">
                        <img src="https://img3.doubanio.com/icon/u39561667-4.jpg"/>
                    </div>
                    <div class="col-md-8 user-review-comment-area">
                        <div class="col-md-12">
                            <span>{{ review_comment.user.nickname }}</span>
                            <span>{{ review_comment.comment_time }}</span>
                            <a href="#" class="review-comment-delete">删除</a>
                        </div>
                        <div class="col-md-12">
                            <div>{{ review_comment.content }}</div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <form id="user_comment_form" onsubmit="return false;">
                {% csrf_token %}
                <div class="row">
                    <input type="hidden" name="review" value="{{ review.id }}"/>
                    <div class="col-md-1">
                        <img src="https://img3.doubanio.com/icon/u155403369-3.jpg"/>
                    </div>
                    <div class="col-md-8 form-group">
                        <textarea id="user_comment_content_textarea" class="form-control" name="content" rows="3" placeholder="说点儿什么吧"></textarea>
                    </div>
                    <div class="col-md-offset-1 col-md-8">
                        <a class="btn btn-default" role="button" onclick="submit_review_comment()">
                            <span class="glyphicon glyphicon-pushpin" aria-hidden="true"></span>
                        </a>
                    </div>
                </div>
            </form>
        </div>

        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page={{ page_obj.previous_page_number }}#user-review-comment">上一页</a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}#user-review-comment">下一页</a>
                        {% endif %}
                    </span>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        function submit_review_likes(is_to_add) {
            var url
            if(is_to_add){
                url = "{% url 'reviews:add_review_likes' %}"
            } else {
                url = "{% url 'reviews:delete_review_likes' %}"
            }
            $.ajax({
		             type: "POST",
		             url: url,
		             data: $('#review_likes_form').serialize(),
		             dataType: "json",
		             success: function(data){
                         window.history.go(0)
		             }
            });
        }

        function submit_review_comment() {
            if($('#user_comment_content_textarea').val()) {
                $.ajax({
                    type: "POST",
                    url: "{% url 'reviews:add_review_comment' %}",
                    data: $('#user_comment_form').serialize(),
                    dataType: "json",
                    success: function (data) {
                        history.go(0)
                    },
                    error: function (XMLHttpRequest, textStatus, errorThrown) {
                        alert('服务器错误，请稍后重试！')
                    }
                });
            }
        }

        $(function () {
            $('.user-review-comment-area').each(function (i) {
                $(this).mouseover(function () {
                    $('.review-comment-delete').show()
                })
                $(this).mouseout(function () {
                    $('.review-comment-delete').hide()
                })
            })
        })
    </script>
{% endblock %}

templates/drama/review_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{ drama.title_cn }}的剧评{% endblock %}

{% block content %}
    <div class="container">
        <!-- 评论开始 -->
        <div>
            <div class="row">
                <div class="col-md-12">
                    <h2>{{ drama.title_cn }}的剧评(全部共<mark>{{ paginator.count }}</mark>条)</h2>
                </div>
            </div>

            {% for review in object_list %}
                <div>
                    <div class="row">
                        <div class="col-md-9">
                            <div class="review-list-title">
                                <a href="{% url 'reviews:review_detail' review.id %}"><span>{{ review.title }}</span></a>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-xs-6 col-md-9 review-list-user-info">
                            <img src="https://img3.doubanio.com/icon/u39561667-4.jpg"/>
                            <span>{{ review.user.nickname }}</span>

                            {% load my_tag %}
                            {% divide review.rating 2 as stars %}
                            <span class="review-list-rating" data-value="{{ review.rating }}">
                            {% for i in stars|times %}
                                <i class="glyphicon glyphicon-star"></i>
                            {% endfor %}
                        </span>
                            <span>{{ review.pubtime }}</span>
                            <div class="review-list-like">
                                <span class="glyphicon glyphicon-thumbs-up"></span>
                                <span>{{ review.review_likes.count }}</span>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-xs-6 col-md-9 review-list-user-info">
                            <p>{{ review.content|truncatechars:200 }}
                                <mark><a href="#">共{{ review.review_comments.count }}回应</a></mark>
                            </p>
                        </div>
                    </div>
                </div>

            {% endfor %}
            <!-- 评论结束 -->

            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="pagination">
                        <span class="step-links">
                            {% if page_obj.has_previous %}
                                <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
                            {% endif %}

                            <span class="current">
                                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                            </span>

                            {% if page_obj.has_next %}
                                <a href="?page={{ page_obj.next_page_number }}">下一页</a>
                            {% endif %}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
{% endblock %}